version: '3.8'

services:
  daleel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Expose port 5000 to access the app on localhost:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app  # Mounts local changes for development, remove in production