version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=your_connection_string_here
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 